1.18.10blankon1

diff --git a/debian/dpkg.prerm b/debian/dpkg.prerm
--- a/debian/dpkg.prerm
+++ b/debian/dpkg.prerm
@@ -7,7 +7,7 @@
 # Before an upgrade:
 #      <old-prerm> upgrade <new-version>
 # if that fails:
-#      <new-prerm> failed-upgrade <old-version>
+#      <new-prerm> failed-upgrade <old-version> <new-version>
 #
 #
 # Before package is deconfigured while dependency is replaced due to conflict:
@@ -156,7 +156,7 @@ case "$1" in
         ;;
 
     *)
-        echo "$0 called with unknown argument \`$1'" 1>&2
+        echo "$0 called with unknown argument '$1'" 1>&2
         exit 1
         ;;
 esac
